export const AUDIT_ACTIONS = {
  CREATE_SHIFTPLAN: "CREATE_SHIFTPLAN",
  UPDATE_SHIFTPLAN: "UPDATE_SHIFTPLAN",
  DELETE_SHIFTPLAN: "DELETE_SHIFTPLAN",
  CREATE_WORKLOG: "CREATE_WORKLOG",
  UPDATE_WORKLOG: "UPDATE_WORKLOG",
  APPROVE_LEAVE: "APPROVE_LEAVE",
  REJECT_LEAVE: "REJECT_LEAVE",
  ADD_TEAM_MEMBER: "ADD_TEAM_MEMBER",
  REMOVE_TEAM_MEMBER: "REMOVE_TEAM_MEMBER",
  AUTO_MARK_UNLOGGED: "AUTO_MARK_UNLOGGED",
};
